server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /var/www/court-lab;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript application/json;

    location /data/ {
        expires 1h;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ /index.html;
        expires 5m;
        add_header Cache-Control "public";
        add_header X-Content-Type-Options nosniff;
    }
}
